name: build-iOS
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Build for iOS
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true
        
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**','ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: iOS
          unityVersion: auto

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
