name: build-standalone
on:
  push:
    branches:
      - production
      - 'releases/**'
jobs:
  build:
    name: Build for StandaloneWindows64
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true
        
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**','ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - uses: game-ci/unity-builder@v2
        evn:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ sercets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: auto

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build